### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [automata/awesome-jamstack#104]
Hey, I found some broken links:

- [x] https://appernetic.io (file: README.md, error: EAI_AGAIN)
- [x] https://github.com/staticwebdev/awesome-azure-static-web-apps%5D (file: README.md, status code: 404)
- [x] https://tipe.io (file: README.md, status code: 404)
- [x] https://jexia.com (file: README.md, error: EAI_AGAIN)
- [x] https://statickit.com (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://www.livemart.store (file: README.md, error: ECONNRESET)
- [x] https://www.elastictable.com (file: README.md, error: ENOTFOUND)
- [x] https://www.tomango.co.uk/thinks/paul-the-octopus-2018/ (file: README.md, status code: 404)
- [x] https://tracker.kontent.ai/592920/state-of-the-headless-cms-market-2020 (file: README.md, error: ECONNREFUSED)

**Comment by automata** [comment]
All referred links removed. Thank you for pointing them out @ndsvw!
